import { Suspense } from 'react'
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import Sidebar from '@/components/Ui/SideBar';
import Header from '@/components/Ui/Header';
import Footer from '@/components/Ui/Footer';

import '@/styles/app.scss'


const noto = Noto_Sans_JP({
  weight: ["400", "700"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default:'fukumi',
    template: '%s | fukumi'
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang='ja'>
      <body className={noto.className}>
      <AppRouterCacheProvider
        options={{ key: 'css' }}
      >
        <Suspense>
          <Header />
          <div className='l_global_container'>
              <Sidebar />
            <main className='l_main'>
              <div className='l_container'>
                {children}
              </div>
            </main>
          </div>
          <Footer />
        </Suspense>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
