import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "@/components/SideBar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "@/styles/global/globals.css"
import '@/styles/layout/global_container.scss'
import '@/styles/layout/header.scss'
import '@/styles/layout/main.scss'
import '@/styles/layout/container.scss'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default:"fukumi",
    template: '%s | fukumi'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        <div className="l_global_container">
          <Sidebar />
          <main className="l_main">
            <div className="l_container">
              {children}
            </div>
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
