name: Nextjs Build debug

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{ts,tsx}'
          fail_on_error: true

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Get date info
        id: date
        run: |
          echo "week=$(date +%Y-%V)" >> $GITHUB_OUTPUT

      - run: node --version

      - name: cache-node-modules
        uses: actions/cache@v4
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: cache-nextjs-build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-build-${{ steps.date.outputs.week }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-build-${{ steps.date.outputs.week }}-

      - name: npm-install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm i

      - name: markuplint
        run: npm run markuplint

      - name: app-build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Clear old cache
        run: |
          find .next/cache -type f -mtime +30 -delete 2>/dev/null || true
